abstract class AppConfig {
  String get env;
  bool get useFirebase;
  String get generationApiBaseUrl;

  /// Firebase options — null when [useFirebase] is false.
  FirebaseOptions? get firebaseOptions;
}

/// Placeholder type; real apps use firebase_options.dart generated by FlutterFire CLI.
class FirebaseOptions {
  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String storageBucket;

  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    required this.storageBucket,
  });
}
